"""
claude_decode.py — Calls Claude API to run PMM, frontend, and design
decode prompts against the generated report. Saves three markdown files.
"""

import os
import anthropic
from pathlib import Path


DECODES = [
    {
        "name": "pmm",
        "prompt_file": "prompts/pmm_decode.md",
        "output_file": "pmm-decode.md",
        "label": "PMM + Brand Decode",
    },
    {
        "name": "frontend",
        "prompt_file": "prompts/frontend_decode.md",
        "output_file": "frontend-decode.md",
        "label": "Frontend Developer Decode",
    },
    {
        "name": "design",
        "prompt_file": "prompts/design_decode.md",
        "output_file": "design-decode.md",
        "label": "Design + Illustration Decode",
    },
]


def run_decode(prompt_text: str, report_text: str, label: str) -> str:
    """Send prompt + report to Claude and return the response."""
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        raise ValueError("ANTHROPIC_API_KEY environment variable not set")

    client = anthropic.Anthropic(api_key=api_key)

    message = client.messages.create(
        model="claude-opus-4-6",
        max_tokens=4096,
        messages=[
            {
                "role": "user",
                "content": f"{prompt_text}\n\n---\n\n## Analysis Report\n\n{report_text}",
            }
        ],
    )

    return message.content[0].text


def run_all(
    report_path: str,
    domain: str,
    output_dir: Path,
    run_id: str = "",
    screenshots_dir=None,
) -> list:
    """Run all three decodes and save outputs. Returns list of saved file paths."""
    output_dir.mkdir(parents=True, exist_ok=True)

    report_text = Path(report_path).read_text(encoding="utf-8")
    saved = []

    for decode in DECODES:
        prompt_path = Path(decode["prompt_file"])
        if not prompt_path.exists():
            print(f"  ! Prompt file not found: {prompt_path}")
            continue

        prompt_text = prompt_path.read_text(encoding="utf-8")

        print(f"  → Running {decode['label']}...")
        try:
            result = run_decode(prompt_text, report_text, decode["label"])

            out_path = output_dir / decode["output_file"]
            header = f"# {decode['label']}: {domain}\n\n> Generated by Claude claude-opus-4-6\n\n---\n\n"
            out_path.write_text(header + result, encoding="utf-8")
            saved.append(str(out_path))
            print(f"    ✓ Saved: {out_path}")

        except Exception as e:
            print(f"  ! {decode['label']} failed: {e}")

    # Step 4: Generate PPT content JSON
    if run_id:
        from tools import ppt_content
        try:
            ppt_path = ppt_content.generate(
                report_path=report_path,
                domain=domain,
                run_id=run_id,
                decodes_dir=output_dir,
                output_dir=output_dir,
            )
            if ppt_path:
                saved.append(ppt_path)
        except Exception as e:
            print(f"  ! PPT content generation failed: {e}")

    return saved
